spring:
  application:
    name: final-notice

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: ${HOTEL_DB_JDBC_URL}
    username: ${HOTEL_DB_USERNAME}
    password: ${HOTEL_DB_PASSWORD}

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  type-aliases-package: com.spring.app.js.notice.domain

server:
  port: ${SERVER_PORT:8002}
  forward-headers-strategy: framework

jwt:
  secret: ${HOTEL_JWT_SECRET}

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://52.78.215.25:8761/eureka/

logging:
  level:
    '[com.spring.app]': debug
    com.netflix.discovery: WARN
    org.springframework.cloud.netflix.eureka: WARN


